# Generated by Django 5.0.1 on 2024-02-09 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0002_remove_customuser_active_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPropose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_a', models.CharField(max_length=150)),
                ('party_b', models.CharField(max_length=150)),
                ('propose_id', models.CharField(max_length=150, unique=True)),
                ('accepte', models.BooleanField()),
                ('propose_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='verify_paid',
            field=models.BooleanField(default=False),
        ),
    ]
