# Generated by Django 5.0.1 on 2024-02-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0003_userpropose_customuser_verify_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpropose',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userpropose',
            name='accepte',
            field=models.BooleanField(default=None),
        ),
    ]
