# Generated by Django 5.0.1 on 2024-02-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0004_userpropose_count_alter_userpropose_accepte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpropose',
            name='accepte',
            field=models.BooleanField(null=True),
        ),
    ]
