# Generated by Django 5.0.1 on 2024-02-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0006_remove_userpropose_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpropose',
            name='sing_1',
            field=models.ImageField(blank=True, null=True, upload_to='sing_1'),
        ),
        migrations.AddField(
            model_name='userpropose',
            name='sing_2',
            field=models.ImageField(blank=True, null=True, upload_to='sing_2'),
        ),
    ]
