# Generated by Django 5.0.1 on 2024-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0007_userpropose_sing_1_userpropose_sing_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpropose',
            name='re_props',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
